name: Deploy static site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare public directory
        run: |
          rm -rf public
          mkdir public
          # Copy site files to public, excluding .git and workflow files
          rsync -av --exclude='.git' --exclude='.github' --exclude='.gitignore' --exclude='README.md' ./ public/

      - name: Configure Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact for deployment
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
