name: Build and deploy static site to GitHub Pages (gh-pages)

on:
  push:
    branches:
      - main

# Need contents: write so the action can push to gh-pages branch using GITHUB_TOKEN
permissions:
  contents: write
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare public directory
        run: |
          rm -rf public || true
          mkdir public
          # Copy site files to public, excluding git metadata and workflow files
          rsync -av --exclude='.git' --exclude='.github' --exclude='.gitignore' --exclude='README.md' ./ public/

      - name: Show public contents (debug)
        run: |
          echo "==== public/ listing ===="
          ls -la public || true

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          # optional: keep a clean history or allow empty commits
          allow_empty_commit: true
